/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Dimension;
import java.awt.Toolkit;
import lamhdt.dtos.UserDTO;
import lamhdt.model.UserDAO;

/**
 *
 * @author HL
 */
public class ChangeAccountUI extends javax.swing.JFrame {

    private int offsetX, offsetY;
    private UserDTO dto = null;
    private String username;
    private String password;
    private Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form ChangeAccountUI
     */
    class Noti implements Runnable {

        Thread t = null;
        String noti;

        public Noti(String noti) {
            this.noti = noti;
            t = new Thread(this);
            t.start();

        }

        @Override
        public void run() {
            try {
                lbNoti.setText(noti);
                t.sleep(3000);
                lbNoti.setText("CHANGE LOGIN INFOMATION");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public ChangeAccountUI() {
        initComponents();
        this.setLocation(ss.width / 2 - this.getSize().width / 2, ss.height / 2 - this.getSize().height / 2);
        btnCancelAccount.setVisible(false);
        btnOKAccount.setVisible(false);
        btnCancelPassword.setVisible(false);
        btnOKPassword.setVisible(false);
        txtPassword.setText("hi");

    }

    public ChangeAccountUI(UserDTO user) {
        initComponents();
        dto = user;
        this.username = dto.getUsername();
        this.password = dto.getPassword();
        if(dto.getUsername().equals("admin"))
            btnEditAccount.setVisible(false);
        this.setLocation(ss.width / 2 - this.getSize().width / 2, ss.height / 2 - this.getSize().height / 2);
        btnCancelAccount.setVisible(false);
        btnOKAccount.setVisible(false);
        btnCancelPassword.setVisible(false);
        btnOKPassword.setVisible(false);
        txtUsername.setText(dto.getUsername());
        txtPassword.setText(dto.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbNoti = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        AccountGr = new javax.swing.JPanel();
        titleAccount = new javax.swing.JPanel();
        lbAc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        containerAccount = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        btnEditAccount = new javax.swing.JButton();
        btnOKAccount = new javax.swing.JButton();
        btnCancelAccount = new javax.swing.JButton();
        AccountGr1 = new javax.swing.JPanel();
        titleAccount1 = new javax.swing.JPanel();
        lbAc1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        containerAccount1 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnEditPassword = new javax.swing.JButton();
        btnOKPassword = new javax.swing.JButton();
        btnCancelPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Account");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(530, 447));

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(759, 70));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, -4));

        jLabel2.setFont(new java.awt.Font("SVN-SAF", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setOpaque(false);
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        lbNoti.setFont(new java.awt.Font("SVN-SAF", 0, 28)); // NOI18N
        lbNoti.setForeground(new java.awt.Color(255, 255, 255));
        lbNoti.setText("CHANGE LOGIN INFOMATION");
        jPanel3.add(lbNoti);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        container.setBackground(new java.awt.Color(242, 242, 242));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(255, 0, 51)));

        AccountGr.setBackground(new java.awt.Color(255, 255, 255));
        AccountGr.setOpaque(false);
        AccountGr.setPreferredSize(new java.awt.Dimension(370, 130));
        AccountGr.setLayout(new java.awt.BorderLayout());

        titleAccount.setBackground(new java.awt.Color(255, 255, 255));
        titleAccount.setOpaque(false);
        titleAccount.setPreferredSize(new java.awt.Dimension(333, 40));
        titleAccount.setLayout(new java.awt.BorderLayout(10, 10));

        lbAc.setBackground(new java.awt.Color(255, 255, 255));
        lbAc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(0, 51, 255), new java.awt.Color(255, 254, 255), new java.awt.Color(255, 254, 255)));
        lbAc.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel3.setFont(new java.awt.Font("SVN-SAF", 0, 18)); // NOI18N
        jLabel3.setText("ACCOUNT");
        lbAc.add(jLabel3);

        titleAccount.add(lbAc, java.awt.BorderLayout.LINE_START);

        AccountGr.add(titleAccount, java.awt.BorderLayout.PAGE_START);

        containerAccount.setBackground(new java.awt.Color(255, 255, 255));
        containerAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(255, 0, 51), new java.awt.Color(0, 51, 255)));
        containerAccount.setPreferredSize(new java.awt.Dimension(370, 75));
        containerAccount.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 25));

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("SVN-SAF", 0, 15)); // NOI18N
        txtUsername.setText("ACCount");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(33, 33, 33)));
        txtUsername.setPreferredSize(new java.awt.Dimension(250, 35));
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsernameMouseExited(evt);
            }
        });
        containerAccount.add(txtUsername);

        btnEditAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnEditAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_edit_file_24px.png"))); // NOI18N
        btnEditAccount.setPreferredSize(new java.awt.Dimension(57, 35));
        btnEditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccountActionPerformed(evt);
            }
        });
        containerAccount.add(btnEditAccount);

        btnOKAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnOKAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_checked_checkbox_24px.png"))); // NOI18N
        btnOKAccount.setPreferredSize(new java.awt.Dimension(57, 35));
        btnOKAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKAccountActionPerformed(evt);
            }
        });
        containerAccount.add(btnOKAccount);

        btnCancelAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelAccount.setFont(new java.awt.Font("SVN-SAF", 0, 18)); // NOI18N
        btnCancelAccount.setText("X");
        btnCancelAccount.setPreferredSize(new java.awt.Dimension(45, 35));
        btnCancelAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAccountActionPerformed(evt);
            }
        });
        containerAccount.add(btnCancelAccount);

        AccountGr.add(containerAccount, java.awt.BorderLayout.CENTER);

        AccountGr1.setBackground(new java.awt.Color(255, 255, 255));
        AccountGr1.setOpaque(false);
        AccountGr1.setPreferredSize(new java.awt.Dimension(370, 130));
        AccountGr1.setLayout(new java.awt.BorderLayout());

        titleAccount1.setBackground(new java.awt.Color(255, 255, 255));
        titleAccount1.setOpaque(false);
        titleAccount1.setLayout(new java.awt.BorderLayout(10, 10));

        lbAc1.setBackground(new java.awt.Color(255, 255, 255));
        lbAc1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(0, 51, 255), new java.awt.Color(255, 254, 255), new java.awt.Color(255, 254, 255)));
        lbAc1.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel4.setFont(new java.awt.Font("SVN-SAF", 0, 18)); // NOI18N
        jLabel4.setText("PASSWORD");
        lbAc1.add(jLabel4);

        titleAccount1.add(lbAc1, java.awt.BorderLayout.LINE_START);

        AccountGr1.add(titleAccount1, java.awt.BorderLayout.PAGE_START);

        containerAccount1.setBackground(new java.awt.Color(255, 255, 255));
        containerAccount1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(255, 0, 51), new java.awt.Color(0, 51, 255)));
        containerAccount1.setPreferredSize(new java.awt.Dimension(370, 75));
        containerAccount1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 25));

        txtPassword.setEditable(false);
        txtPassword.setFont(new java.awt.Font("SVN-Segoe Print", 0, 16)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(33, 33, 33)));
        txtPassword.setPreferredSize(new java.awt.Dimension(250, 35));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPasswordMouseExited(evt);
            }
        });
        containerAccount1.add(txtPassword);

        btnEditPassword.setBackground(new java.awt.Color(255, 255, 255));
        btnEditPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_edit_file_24px.png"))); // NOI18N
        btnEditPassword.setPreferredSize(new java.awt.Dimension(57, 35));
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });
        containerAccount1.add(btnEditPassword);

        btnOKPassword.setBackground(new java.awt.Color(255, 255, 255));
        btnOKPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_checked_checkbox_24px.png"))); // NOI18N
        btnOKPassword.setPreferredSize(new java.awt.Dimension(57, 35));
        btnOKPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKPasswordActionPerformed(evt);
            }
        });
        containerAccount1.add(btnOKPassword);

        btnCancelPassword.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelPassword.setFont(new java.awt.Font("SVN-SAF", 0, 18)); // NOI18N
        btnCancelPassword.setText("X");
        btnCancelPassword.setPreferredSize(new java.awt.Dimension(45, 35));
        btnCancelPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPasswordActionPerformed(evt);
            }
        });
        containerAccount1.add(btnCancelPassword);

        AccountGr1.add(containerAccount1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(AccountGr, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(AccountGr1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AccountGr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(AccountGr1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        this.dispose();
        new UI(dto.getPermision(), dto.getUsername(), dto.getPassword()).setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        offsetX = evt.getX();
        offsetY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(evt.getXOnScreen() - offsetX, evt.getYOnScreen() - offsetY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnEditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccountActionPerformed
        btnCancelAccount.setVisible(true);
        btnOKAccount.setVisible(true);
        txtUsername.setEditable(true);
        btnEditAccount.setVisible(false);
    }//GEN-LAST:event_btnEditAccountActionPerformed

    private void txtUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseEntered
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 51, 255)));
    }//GEN-LAST:event_txtUsernameMouseEntered

    private void txtUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseExited
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(33, 33, 33)));
    }//GEN-LAST:event_txtUsernameMouseExited

    private void btnCancelAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAccountActionPerformed
        txtUsername.setEditable(false);
        btnCancelAccount.setVisible(false);
        btnEditAccount.setVisible(true);
        btnOKAccount.setVisible(false);
    }//GEN-LAST:event_btnCancelAccountActionPerformed

    private void txtPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseEntered
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 51, 255)));
    }//GEN-LAST:event_txtPasswordMouseEntered

    private void txtPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseExited
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(33, 33, 33)));
    }//GEN-LAST:event_txtPasswordMouseExited

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        btnCancelPassword.setVisible(true);
        btnOKPassword.setVisible(true);
        txtPassword.setEditable(true);
        btnEditPassword.setVisible(false);
    }//GEN-LAST:event_btnEditPasswordActionPerformed

    private void btnCancelPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPasswordActionPerformed
        txtPassword.setEditable(false);
        btnCancelPassword.setVisible(false);
        btnEditPassword.setVisible(true);
        btnOKPassword.setVisible(false);
    }//GEN-LAST:event_btnCancelPasswordActionPerformed

    private void btnOKAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKAccountActionPerformed
        if (txtUsername.getText().trim().equals("")) {
            new Noti("Username is not empty");
            return;
        }
        if (!txtUsername.getText().trim().matches("[A-Za-z0-9]+")) {
            new Noti("Username must be (A-z0-9)");
            return;
        }
        if (txtUsername.getText().trim().equalsIgnoreCase("Account")) {
            new Noti("Username mustn't be \"Account\"");
            return;
        }
        if (!txtUsername.getText().equals(username)) {
            UserDAO dao = new UserDAO();
            try {
                boolean as = dao.updateInfo(txtUsername.getText(), username);
                
                if(as){
                    username = txtUsername.getText();
                    dto.setUsername(txtUsername.getText());
                    new Noti("Successfully");
                }
            } catch (Exception e) {
                new Noti("Username already exists");
                txtUsername.setText(username);
            }
        }
        btnCancelAccountActionPerformed(evt);
    }//GEN-LAST:event_btnOKAccountActionPerformed

    private void btnOKPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKPasswordActionPerformed
        String pass = txtPassword.getText();
        if (pass.trim().equals("")) {
            new Noti("Password is not empty");
            return;
        }
        if (!pass.trim().matches("[A-Za-z0-9]+")) {
            new Noti("Password must be (A-z0-9)");
            return;
        }
        if (!pass.equals(password)) {
            UserDAO dao = new UserDAO();
            try {
                UserDTO user = new UserDTO(username, pass);
                if (dao.changePassword(user)) {
                    password = pass;
                    user.setPassword(txtPassword.getText());
                    new Noti("Successfully");
                }
            } catch (Exception e) {
                e.printStackTrace();
                new Noti("Fail");
                txtPassword.setText(password);
            }
        }
         btnCancelPasswordActionPerformed(evt);
    }//GEN-LAST:event_btnOKPasswordActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeAccountUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountGr;
    private javax.swing.JPanel AccountGr1;
    private javax.swing.JButton btnCancelAccount;
    private javax.swing.JButton btnCancelPassword;
    private javax.swing.JButton btnEditAccount;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnOKAccount;
    private javax.swing.JButton btnOKPassword;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerAccount;
    private javax.swing.JPanel containerAccount1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lbAc;
    private javax.swing.JPanel lbAc1;
    private javax.swing.JLabel lbNoti;
    private javax.swing.JPanel titleAccount;
    private javax.swing.JPanel titleAccount1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
