/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lamhdt.dtos.EquipmentDTO;
import lamhdt.dtos.RoleDTO;
import lamhdt.model.TribulationDAO;
import lamhdt.model.UsedEquipmentDAO;
import lamhdt.model.UsedRoleDAO;

/**
 *
 * @author HL
 */
public class ShowTable extends javax.swing.JFrame {
    Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
    int offsetX , offsetY;
    DefaultTableModel tblModelShow;
    /**
     * Creates new form ShowTable
     */
    
    private void initMessage(){
        JOptionPane.showMessageDialog(this, "No Data to Show");
    }
    public  void RoleInit(int id)
    {
         tblModelShow.addColumn("Role Name");
        try {
             UsedRoleDAO dao = new UsedRoleDAO();
         List<RoleDTO> list = dao.getAllRoleByTribulationID(id);
         if(list.isEmpty()) {
             System.out.println("1");
             initMessage();
         }else {
             this.setVisible(true);
         }
         showRole(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }
    public  void EquipmentInit(int id)
    {
        tblModelShow.addColumn("Equipment Name");
        tblModelShow.addColumn("Quantity");
        try {
             UsedEquipmentDAO dao = new UsedEquipmentDAO();
         List<EquipmentDTO> list = dao.getAllEquipmentByTribulationID(id);
         if(list.isEmpty()) {
             initMessage();
         }else {
             this.setVisible(true);
         }
         
         showEquipment(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void TribulationInit(int equipmentID){
        tblModelShow.addColumn("Tribulation Name");
        tblModelShow.addColumn("From");
        tblModelShow.addColumn("To"); 
        tblModelShow.addColumn("Quantity");
        this.setSize(new Dimension(600, 400));
        try {
            TribulationDAO dao = new TribulationDAO();
            List rs = dao.getTribulationByEquipmentID(equipmentID);
            if(rs.isEmpty())
                initMessage();
            else{
                this.setVisible(true);
            }
            showTribulation(rs);   
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void Myinit()
    {
        tblModelShow = (DefaultTableModel) tblShowView.getModel();
        tblShowView.getTableHeader().setFont(new java.awt.Font("SVN-Linux Libertine", 0, 17));
        tblShowView.getTableHeader().setBorder(UIManager.getBorder("TableHeader.cellBorder"));
    }
    private void showRole(List<RoleDTO> list) throws  Exception{
        try {
            tblModelShow.setRowCount(0);
            for (RoleDTO roleDAO : list) {
                tblModelShow.addRow(roleDAO.toVector());
            }
        } catch (Exception e) {
        }
    }
    private void showEquipment(List<EquipmentDTO> list) throws Exception{
        try {
            tblModelShow.setRowCount(0);
            for (EquipmentDTO equipmentDTO : list) {
                tblModelShow.addRow(equipmentDTO.toVectorShow());
            }
        } catch (Exception e) {
        }
    }
    
    private void showTribulation(List list) throws Exception{
        try {
            tblModelShow.setRowCount(0);
            for (Object object : list) {
                tblModelShow.addRow((Vector<?>) object);
            }
        } catch (Exception e) {
        }
    }
    public ShowTable() {
        initComponents();
        setSize(new Dimension(300, 475));
        Myinit();
        this.setLocation(ss.width/2 - this.getSize().width/2, ss.height/2 - this.getSize().height/2);
        
    }

    public ShowTable(String table) {
        initComponents();
        setSize(new Dimension(300, 475));
        Myinit();
        this.setLocation(ss.width/2 - this.getSize().width/2, ss.height/2 - this.getSize().height/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Show Infomation");
        setAlwaysOnTop(true);
        setUndecorated(true);

        titleBar.setBackground(new java.awt.Color(255, 255, 255));
        titleBar.setPreferredSize(new java.awt.Dimension(576, 30));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_close_window_24px.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(5, 5, 5))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(titleBar, java.awt.BorderLayout.PAGE_START);

        main.setLayout(new java.awt.GridLayout(1, 0));

        tblShowView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblShowView.setFocusable(false);
        tblShowView.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblShowView.setRowHeight(25);
        tblShowView.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblShowView.setShowHorizontalLines(false);
        tblShowView.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblShowView);

        main.add(jScrollPane1);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
       this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        offsetX = evt.getX();
        offsetY = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
       this.setLocation(evt.getXOnScreen() - offsetX, evt.getYOnScreen() - offsetY);
    }//GEN-LAST:event_titleBarMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main;
    private javax.swing.JTable tblShowView;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
